services:
#  app:
#    container_name: speedrunning-leaderboard-app
#    build: ./
#    depends_on:
#      redis:
#        condition: service_healthy
#      postgres:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
#      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
#    networks:
#      - backend
#    volumes:
#      - ./src:/app/cached

  redis:
    image: redis:alpine
    container_name: speedrunning-leaderboard-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:alpine
    container_name: speedrunning-leaderboard-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d leaderboard" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge