spring:
  application:
    name: realtime-leaderboard
  data:
    redis:
      port: 6379
      host: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: LeaderboardHikariCP
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
