spring:
  application:
    name: realtime-leaderboard
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboard
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: LeaderboardHikariCP
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:init-data/init-role.sql
      continue-on-error: true


jwt:
  public-key: classpath:app.pub
  private-key: classpath:app.key
  access-expiry: 3600000  # 1 hour
  refresh-expiry: 604800000  # 7 days


logging:
  level:
    root: warn
    org.springframework.web: debug
    org.springframework.security: debug
    vn.pvhg.leaderboard: debug